### PR TITLE
Allow custom separator to be used in text

### PR DESCRIPTION
**Pull request by peterzhu2118**
Adds a option `separator` which allows custom separators that can be set by the user.

### CODE REVIEW

**Comment by peterzhu2118** [comment]
CI failure seems to be unrelated (I think it's caused by the old Ruby versions you're testing against).

**Comment by ArturT** [comment]
@peterzhu2118 Thanks for PR. Can you update README and add info about `separator` and what it is for?

If you could try to fix CI or add a new Ruby version to test it on CI that would be great. I did not touch this project for a long time.

**Comment by peterzhu2118** [comment]
Hey @ArturT, thanks for the really fast response! I've updated the readme, please let me know how it looks! I've also updated travis to test on Ruby 2.6, 2.5, 2.4, 2.3. The tests seem to pass now.

**Comment by ArturT** [comment]
I've released new version `avatarly` 1.6.0

**Pull request merged**
